FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python3 build_db.py --db-path /app/block_db.sqlite --classify-dir testdata --data-dir /app/data/mainnet/training/slots_1_to_4102000
RUN ls -l /app

EXPOSE 8000

WORKDIR /app/scripts

ENTRYPOINT ["./start_server_docker.sh"]
