
FROM python:3.11

WORKDIR /app

COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip list -v

COPY . .

# Set the working directory to where the start script is located
WORKDIR /app/scripts

# Start the application
ENTRYPOINT ["./start_background.sh"]
